---
name: Manual Publish to NPM

# Allow manual triggering of npm publish with OTP support
on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type (patch, minor, major, or skip)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - skip

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install dependencies
        run: npm ci

      - name: Lint code (optional)
        run: >
          npm run lint || echo "Linting failed or not configured, continuing..."
        continue-on-error: true

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Bump version
        if: inputs.version_bump != 'skip'
        run: |
          npm version ${{ inputs.version_bump }} --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Get current version
        if: inputs.version_bump == 'skip'
        run: |
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Check if version already published
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          echo "Checking if $PACKAGE_NAME@$NEW_VERSION is already published..."

          npm_view_result=$(npm view "$PACKAGE_NAME@$NEW_VERSION" version 2>/dev/null || echo "")
          if [ -n "$npm_view_result" ]; then
            echo "Version $NEW_VERSION is already published!"
            echo "Please choose a different version bump or use 'skip'"
            echo "if you've manually updated package.json"
            exit 1
          else
            echo "Version $NEW_VERSION is not yet published. Proceeding..."
          fi

      - name: Commit and push version bump
        if: inputs.version_bump != 'skip'
        run: |
          CURRENT_BRANCH=$(git branch --show-current)
          echo "Current branch: $CURRENT_BRANCH"
          
          git add package.json package-lock.json
          git commit -m "chore: bump version to $NEW_VERSION"
          git tag "v$NEW_VERSION"

          # Push to current branch
          git push origin $CURRENT_BRANCH --tags

          # If we're on main, we're done
          if [ "$CURRENT_BRANCH" = "main" ]; then
            echo "Pushed to main branch"
          else
            echo "Pushed to $CURRENT_BRANCH branch"
            echo "Note: You may want to merge this to main later"
          fi

      - name: Verify package contents
        run: npm pack --dry-run

      - name: Publish to NPM with OTP support
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          # This action supports interactive OTP input if 2FA is enabled
