---
name: Publish to NPM

# Trigger this workflow when a new release is created
on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Lint code (optional)
        run: >
          npm run lint || echo "Linting failed or not configured, continuing..."
        continue-on-error: true

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Verify package contents
        run: npm pack --dry-run

      - name: Check if version already published
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          echo "Checking if $PACKAGE_NAME@$PACKAGE_VERSION is already published..."

          npm_view_result=$(npm view "$PACKAGE_NAME@$PACKAGE_VERSION" version 2>/dev/null || echo "")
          if [ -n "$npm_view_result" ]; then
            echo "Version $PACKAGE_VERSION is already published!"
            echo "Please update the version in package.json before releasing."
            echo "Current published version: $npm_view_result"
            echo "Version in package.json: $PACKAGE_VERSION"
            exit 1
          else
            echo "Version $PACKAGE_VERSION is not yet published. Proceeding..."
          fi

      - name: Publish to NPM with OTP support
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          # This action supports interactive OTP input if 2FA is enabled
          # It will pause and wait for manual OTP entry in the GitHub Actions UI
